In [1]:
l=[10,20,30,40,50,60,70,80]
print(l)
l.append(200)
print(l)
l.append(300)
print(l)
l.remove(10)
print(l)
l.remove(30)
print(l)
l.sort()
print(l)
l.sort(reverse=True)
print(l)

[10, 20, 30, 40, 50, 60, 70, 80]
[10, 20, 30, 40, 50, 60, 70, 80, 200]
[10, 20, 30, 40, 50, 60, 70, 80, 200, 300]
[20, 30, 40, 50, 60, 70, 80, 200, 300]
[20, 40, 50, 60, 70, 80, 200, 300]
[20, 40, 50, 60, 70, 80, 200, 300]
[300, 200, 80, 70, 60, 50, 40, 20]

In [3]:
T = (45,89.5,76,45.4,89,92,58,45)
highest = max(T)
print(highest)
highest_index = T.index(highest)
print(highest_index)
lowest = min(T)
print(lowest)
lowest_index = T.index(lowest)
print(lowest_index)
reverse_T= list(T[::-1])
print(reverse_T)
user = 76
if user in T:
    index = T.index(user)
    print("present at index",index)
else:
    print("it's not present")

92
5
45
0
[45, 58, 92, 89, 45.4, 76, 89.5, 45]
present at index 2

In [5]:
import random

random_number = [random.randint(100,900) for i in range(100)]
def is_prime(n):
    if n<2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n%i==0:
            return False
        return True

odd_num = [num for num in random_number if num%2!=0]
print(odd_num)
print(len(odd_num))
even_num = [num for num in random_number if num%2==0]
print(even_num)
print(len(even_num))
prime_num = [num for num in random_number if is_prime(num)]
print(prime_num)
print(len(prime_num))

[777, 727, 789, 821, 447, 839, 893, 615, 613, 331, 631, 207, 615, 745, 549, 139, 161, 105, 509, 651, 647, 371, 795, 263, 183, 765, 753, 883, 449, 631, 893, 741, 291, 713, 225, 759, 249, 661, 571, 739, 299, 833, 265, 845, 691, 889, 893, 555, 243, 741]
50
[274, 514, 236, 164, 710, 750, 172, 758, 758, 294, 244, 770, 820, 568, 484, 756, 848, 620, 772, 362, 448, 290, 860, 552, 784, 738, 768, 596, 124, 338, 776, 252, 820, 270, 496, 470, 574, 648, 622, 476, 756, 644, 500, 754, 370, 470, 666, 566, 750, 776]
50
[777, 727, 789, 821, 447, 839, 893, 615, 613, 331, 631, 207, 615, 745, 549, 139, 161, 105, 509, 651, 647, 371, 795, 263, 183, 765, 753, 883, 449, 631, 893, 741, 291, 713, 225, 759, 249, 661, 571, 739, 299, 833, 265, 845, 691, 889, 893, 555, 243, 741]
50

In [7]:
A={34,56,78,90}
B={78,45,90,23}
union_score = A.union(B)
print(union_score)
intersection_score = A.intersection(B)
print(intersection_score)
symmteric_difference = A.symmetric_difference(B)
print(symmteric_difference)
subset = A.issubset(B)
print(subset)
superset = B. issuperset(A)
print(superset)
X = int(input("enter the any number:"))
if X in A:
    print("present in set A")
else:
    print("not present in set A")

{34, 45, 78, 23, 56, 90}
{90, 78}
{34, 45, 23, 56}
False
False

enter the any number: 25

not present in set A

In [9]:
sample_dict = {"name": "Kelly", "age":25, "salary":8000, "city":"New york"}
old_key = "city"
new_key = "location"
sample_dict[new_key]= sample_dict.pop(old_key)
print(sample_dict)

{'name': 'Kelly', 'age': 25, 'salary': 8000, 'location': 'New york'}